[project]
name = "python-google-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arcadepy>=1.10.0",
    "google-adk>=1.19.0",
    "google-adk-arcade>=0.0.2",
    "litellm>=1.80.7",
]