[project]
name = "python-openai-agents-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arcadepy>=1.10.0",
    "openai-agents>=0.6.5",
]